version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: geofirenet_db
    environment:
      POSTGRES_USER: dasunika
      POSTGRES_PASSWORD: geofirenet_dev
      POSTGRES_DB: geofirenet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: geofirenet_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@geofirenet.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
