"""global_hierarchy_active_detection

Revision ID: 2699a1e02be6
Revises: 2a218deae290
Create Date: 2026-03-22 10:26:09.486315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2699a1e02be6'
down_revision: Union[str, Sequence[str], None] = '2a218deae290'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_detection_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('detection_source', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('fire_radiative_power_mw', sa.Float(), nullable=True),
    sa.Column('containment_status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_detection_logs_id'), 'active_detection_logs', ['id'], unique=False)
    op.create_index(op.f('ix_active_detection_logs_timestamp'), 'active_detection_logs', ['timestamp'], unique=False)
    op.add_column('locations', sa.Column('continent', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('country', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('admin_region', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('local_region', sa.String(), nullable=True))
    op.create_index(op.f('ix_locations_admin_region'), 'locations', ['admin_region'], unique=False)
    op.create_index(op.f('ix_locations_continent'), 'locations', ['continent'], unique=False)
    op.create_index(op.f('ix_locations_country'), 'locations', ['country'], unique=False)
    op.create_index(op.f('ix_locations_local_region'), 'locations', ['local_region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_local_region'), table_name='locations')
    op.drop_index(op.f('ix_locations_country'), table_name='locations')
    op.drop_index(op.f('ix_locations_continent'), table_name='locations')
    op.drop_index(op.f('ix_locations_admin_region'), table_name='locations')
    op.drop_column('locations', 'local_region')
    op.drop_column('locations', 'admin_region')
    op.drop_column('locations', 'country')
    op.drop_column('locations', 'continent')
    op.drop_index(op.f('ix_active_detection_logs_timestamp'), table_name='active_detection_logs')
    op.drop_index(op.f('ix_active_detection_logs_id'), table_name='active_detection_logs')
    op.drop_table('active_detection_logs')
    # ### end Alembic commands ###
