"""comprehensive_alerts

Revision ID: 7031cecf7d2d
Revises: 2699a1e02be6
Create Date: 2026-03-22 12:21:25.975985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7031cecf7d2d'
down_revision: Union[str, Sequence[str], None] = '2699a1e02be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('location_id', sa.Integer(), nullable=True))
    op.add_column('alerts', sa.Column('risk_score', sa.Float(), nullable=False))
    op.add_column('alerts', sa.Column('severity', sa.String(), nullable=False))
    op.add_column('alerts', sa.Column('alert_message', sa.String(), nullable=False))
    op.add_column('alerts', sa.Column('key_drivers', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('status', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('triggered_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_foreign_key(None, 'alerts', 'locations', ['location_id'], ['id'])
    op.drop_column('alerts', 'timestamp')
    op.drop_column('alerts', 'is_acknowledged')
    op.drop_column('alerts', 'alert_level')
    op.drop_column('alerts', 'message')
    op.drop_column('alerts', 'acknowledged_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('acknowledged_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('alert_level', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('alerts', sa.Column('is_acknowledged', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('alerts', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.drop_column('alerts', 'updated_at')
    op.drop_column('alerts', 'created_at')
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'triggered_at')
    op.drop_column('alerts', 'status')
    op.drop_column('alerts', 'key_drivers')
    op.drop_column('alerts', 'alert_message')
    op.drop_column('alerts', 'severity')
    op.drop_column('alerts', 'risk_score')
    op.drop_column('alerts', 'location_id')
    # ### end Alembic commands ###
