"""add_risk_level_to_alerts

Revision ID: 80ca4d15641e
Revises: a4a6c8bb396d
Create Date: 2026-05-02 09:03:48.174115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ca4d15641e'
down_revision: Union[str, Sequence[str], None] = 'a4a6c8bb396d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('alerts', sa.Column('risk_level', sa.String(), nullable=True))
    
    # Update existing records based on severity
    op.execute("UPDATE alerts SET risk_level = 'High' WHERE severity = 'high'")
    op.execute("UPDATE alerts SET risk_level = 'Extreme' WHERE severity = 'extreme'")
    op.execute("UPDATE alerts SET risk_level = 'Moderate' WHERE severity = 'moderate'")
    op.execute("UPDATE alerts SET risk_level = 'Low' WHERE risk_level IS NULL")
    
    # Now set it to NOT NULL
    op.alter_column('alerts', 'risk_level', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'risk_level')
    # ### end Alembic commands ###
